-- AlterTable
ALTER TABLE "User" ADD COLUMN     "apiKeyLimit" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "dailyResponseCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "userLimit" INTEGER NOT NULL DEFAULT 0;
